module.exports = {
	GET_APPLICANT_UNCONSIDERED: 'GET_APPLICANT_UNCONSIDERED',
	GET_APPLICANT_CONSIDERED: 'GET_APPLICANT_CONSIDERED',
	GET_APPLICANT_INTERVIEWS: 'GET_APPLICANT_INTERVIEWS',
	GET__APPLICANT_OFFERS: 'GET_APPLICANT_OFFERS'
};
