module.exports = {
  ADD_APP: 'ADD_APP',
  REMOVE_APP: 'REMOVE_APP',
  ACCEPT_APP: 'ACCEPT_APP',
  REJECT_APP: 'REJECT_APP',
  FETCH_APP: 'FETCH_APP',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  VisibilityFilters: {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
  },
};