module.exports = {
	ADVANCE_EMPLOYER_REQUEST: 'ADVANCE_EMPLOYER_REQUEST',
	REVERT_EMPLOYER_REQUEST: 'REVERT_EMPLOYER_REQUEST',
	REJECT_EMPLOYER_REQUEST: 'REJECT_EMPLOYER_REQUEST',
	NEXT_MODAL: 'NEXT_MODAL'
};
