module.exports = { 
	GET_EMPLOYER_UNCONSIDERED: 'GET_EMPLOYER_UNCONSIDERED',
	GET_EMPLOYER_CONSIDERED: 'GET_EMPLOYER_CONSIDERED',
	GET_EMPLOYER_INTERVIEWS: 'GET_EMPLOYER_INTERVIEWS',
	GET_EMPLOYER_OFFERS: 'GET_EMPLOYER_OFFERS' 
}