module.exports = {
  ADD_JOB: 'ADD_JOB',
  REMOVE_JOB: 'REMOVE_JOB',
  APPLY_JOB: 'APPLY_JOB',
  SHOW_FORM: 'SHOW_FORM',
  HIDE_FORM: 'HIDE_FORM',
  FETCH_JOBS: 'FETCH_JOBS',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  VisibilityFilters: {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
  },
};