/*
 * action types
 */

module.exports = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  VisibilityFilters: {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
  },
};
